# NUMPY BASICS

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print("Vector:",array1)
a = array1.reshape(3,5)
print("Two dimensional array:", a)

Vector: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Two dimensional array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [3]:
print("shape:", a.shape)
print("dimension:", a.ndim)
print("data type:", a.dtype.name)
print("size:", a.size)
print("type:", type(a))

shape: (3, 5)
dimension: 2
data type: int32
size: 15
type: <class 'numpy.ndarray'>


In [4]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x+y)
print(x-y)
print(x**2)

[5 7 9]
[-3 -3 -3]
[1 4 9]


In [5]:
a = np.array([1,2,3])
d = a.copy()
print(d)
b = a
c = a
b[0] = 5
print(a,b,c)

[1 2 3]
[5 2 3] [5 2 3] [5 2 3]


In [6]:
a = np.array([1,2,3,4,5,6,7])
print(a[0])
print(a[0:4])

1
[1 2 3 4]


In [7]:
reverse_array = a[::-1]
print(reverse_array)

[7 6 5 4 3 2 1]


In [8]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)
print(b[1,1])
print(b[:,1])
print(b[1,:])
print(b[1,1:4])
print(b[-1,:])
print(b[:,-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
7
[2 7]
[ 6  7  8  9 10]
[7 8 9]
[ 6  7  8  9 10]
[ 5 10]
